# churn prediction means how much happy is person or sad

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
url="https://raw.githubusercontent.com/611noorsaeed/100-days-Scikit-Learn-Tutorials-/refs/heads/main/7%20churn.csv"
df=pd.read_csv(url)

df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# keeping important columns

In [5]:
df=df[['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','Contract','TotalCharges','Churn']]

In [6]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,Month-to-month,29.85,No
1,Male,0,No,No,34,Yes,No,One year,1889.5,No
2,Male,0,No,No,2,Yes,No,Month-to-month,108.15,Yes
3,Male,0,No,No,45,No,No phone service,One year,1840.75,No
4,Female,0,No,No,2,Yes,No,Month-to-month,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,One year,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,One year,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,Month-to-month,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Month-to-month,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Two year,6844.5,No

In [7]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,Month-to-month,29.85,No
1,Male,0,No,No,34,Yes,No,One year,1889.5,No
2,Male,0,No,No,2,Yes,No,Month-to-month,108.15,Yes
3,Male,0,No,No,45,No,No phone service,One year,1840.75,No
4,Female,0,No,No,2,Yes,No,Month-to-month,151.65,Yes

# label encoding

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()

# df['gender'] = label_encoder.fit_transform(df['gender'])
 i would have to do this for each colum with textual data

# but you want to do all at once

In [9]:
# using python

categorical_cols = ['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','Contract','TotalCharges','Churn'] 

for cols in categorical_cols:
    df[cols]= label_encoder.fit_transform(df[cols]) 
# do not use label encoding on numerical values the originals are lost and ranking is given to them based on value

In [10]:
# Correct categorical list — remove numeric columns
categorical_cols = ['gender','SeniorCitizen','Partner','Dependents',
                     'PhoneService','MultipleLines','Contract','Churn']

for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

# Make sure TotalCharges stays numeric (sometimes it loads as string/object)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# tenure also stays as-is (numeric), no encoding needed

In [11]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,29.85,0
1,1,0,0,0,34,1,0,1,1889.50,0
2,1,0,0,0,2,1,0,0,108.15,1
3,1,0,0,0,45,0,1,1,1840.75,0
4,0,0,0,0,2,1,0,0,151.65,1
...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,1,1990.50,0
7039,0,0,1,1,72,1,2,1,7362.90,0
7040,0,0,1,1,11,0,1,0,346.45,0
7041,1,1,1,0,4,1,2,0,306.60,1
7042,1,0,0,0,66,1,0,2,6844.50,0

# jugaad use binary and mapping replace

In [12]:
df2=df.copy()
binary_cols= ['Partner','Dependents','Churn']# when colms has only Yes and No

df2[binary_cols]= df2[binary_cols].replace({'Yes':1,'No':0})

In [13]:
df2

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,29.85,0
1,1,0,0,0,34,1,0,1,1889.50,0
2,1,0,0,0,2,1,0,0,108.15,1
3,1,0,0,0,45,0,1,1,1840.75,0
4,0,0,0,0,2,1,0,0,151.65,1
...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,1,1990.50,0
7039,0,0,1,1,72,1,2,1,7362.90,0
7040,0,0,1,1,11,0,1,0,346.45,0
7041,1,1,1,0,4,1,2,0,306.60,1
7042,1,0,0,0,66,1,0,2,6844.50,0

In [14]:
df3=df.copy()
df3['gender']=df3['gender'].replace({'Female' :0, "Male" :1})

In [15]:
df3

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,29.85,0
1,1,0,0,0,34,1,0,1,1889.50,0
2,1,0,0,0,2,1,0,0,108.15,1
3,1,0,0,0,45,0,1,1,1840.75,0
4,0,0,0,0,2,1,0,0,151.65,1
...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,1,1990.50,0
7039,0,0,1,1,72,1,2,1,7362.90,0
7040,0,0,1,1,11,0,1,0,346.45,0
7041,1,1,1,0,4,1,2,0,306.60,1
7042,1,0,0,0,66,1,0,2,6844.50,0

In [16]:
df # using python loop

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,29.85,0
1,1,0,0,0,34,1,0,1,1889.50,0
2,1,0,0,0,2,1,0,0,108.15,1
3,1,0,0,0,45,0,1,1,1840.75,0
4,0,0,0,0,2,1,0,0,151.65,1
...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,1,1990.50,0
7039,0,0,1,1,72,1,2,1,7362.90,0
7040,0,0,1,1,11,0,1,0,346.45,0
7041,1,1,1,0,4,1,2,0,306.60,1
7042,1,0,0,0,66,1,0,2,6844.50,0

# remeber that regeression does not take null values and when train and test split is done, it capture the data at that moment and if train_test is ran then nan values can not be removed after that

In [17]:
df['TotalCharges']=df['TotalCharges'].fillna(df['TotalCharges'].mean(),inplace=True)

C:\Users\Om\AppData\Local\Temp\ipykernel_29168\1399715742.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['TotalCharges']=df['TotalCharges'].fillna(df['TotalCharges'].mean(),inplace=True)

In [18]:
# split data train and test

In [19]:
x=df.drop('Churn',axis=1)
y=df['Churn']

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
x_train.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges
2142,0,0,0,1,21,1,0,1,1336.800000
1623,0,0,0,0,54,1,2,2,5129.450000
6074,1,0,1,0,1,0,1,0,23.450000
1362,1,0,0,0,4,1,0,0,237.950000
6754,1,0,0,1,0,1,2,2,2283.300441

In [22]:
x_train.info()

<class 'pandas.DataFrame'>
Index: 5634 entries, 2142 to 860
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         5634 non-null   int64
 1   SeniorCitizen  5634 non-null   int64
 2   Partner        5634 non-null   int64
 3   Dependents     5634 non-null   int64
 4   tenure         5634 non-null   int64
 5   PhoneService   5634 non-null   int64
 6   MultipleLines  5634 non-null   int64
 7   Contract       5634 non-null   int64
 8   TotalCharges   5634 non-null   float64
dtypes: float64(1), int64(8)
memory usage: 440.2 KB

In [23]:
x_train['TotalCharges']=pd.to_numeric(x_train['TotalCharges'],errors='coerce')
x_test['TotalCharges']=pd.to_numeric(x_test['TotalCharges'],errors='coerce')

In [24]:
x_train.isnull().sum()

gender           0
SeniorCitizen    0
Partner          0
Dependents       0
tenure           0
PhoneService     0
MultipleLines    0
Contract         0
TotalCharges     0
dtype: int64

In [25]:
x_train['TotalCharges'].fillna(x_train['TotalCharges'].mean(),inplace=True)
x_test['TotalCharges'].fillna(x_test['TotalCharges'].mean(),inplace=True)

C:\Users\Om\AppData\Local\Temp\ipykernel_29168\821571459.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  x_train['TotalCharges'].fillna(x_train['TotalCharges'].mean(),inplace=True)
C:\Users\Om\AppData\Local\Temp\ipykernel_29168\821571459.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  x_test['TotalCharges'].fillna(x_test['TotalCharges'].mean(),inplace=True)

185       24.80
2715     996.45
3825    1031.70
1807      76.35
132     3260.10
         ...
6366    4378.80
315     5686.40
2439     329.75
5002    2960.10
1161      31.35
Name: TotalCharges, Length: 1409, dtype: float64

In [26]:
# stadardize features (optinal in logistic regression)

In [27]:

from sklearn.preprocessing import StandardScaler
scalar= StandardScaler()

In [28]:
x_train=scalar.fit_transform(x_train)
x_test=scalar.transform(x_test)

In [29]:
x_train

array([[-1.02516569, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.42209885],
       [-1.02516569, -0.4377492 , -0.96957859, ...,  1.10833901,
         1.5775905 ,  1.2553663 ],
       [ 0.97545208, -0.4377492 ,  1.03137591, ...,  0.05390099,
        -0.83177379, -1.00298527],
       ...,
       [ 0.97545208, -0.4377492 ,  1.03137591, ..., -1.00053704,
        -0.83177379, -0.87799307],
       [ 0.97545208,  2.28441306, -0.96957859, ...,  1.10833901,
        -0.83177379, -0.48253828],
       [ 0.97545208, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.81109615]], shape=(5634, 9))

In [30]:
print(df['TotalCharges'].isnull().sum()) # reomve null values as it can hinder machine learing in Regression as regression doesn't accept null values

0

In [31]:
print(df['TotalCharges'].isnull().sum())

0

In [32]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [33]:
print(df.isnull().sum())          # check on the full dataframe before split
print(np.isnan(x_train).sum())    # if x_train is a numpy array

gender           0
SeniorCitizen    0
Partner          0
Dependents       0
tenure           0
PhoneService     0
MultipleLines    0
Contract         0
TotalCharges     0
Churn            0
dtype: int64
0

In [34]:
lg.fit(x_train,y_train)
y_pred=lg.predict(x_test)

In [35]:
y_pred

array([1, 0, 0, ..., 0, 0, 1], shape=(1409,))

In [36]:
# accuracy score

In [37]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)

0.7757274662881476

# used for saving the trained model

In [38]:
import pickle

with open('logistic_model.pkl', 'wb') as file:
    pickle.dump(lg, file)

In [39]:
with open('logistic_model.pkl', 'rb') as file:
    model = pickle.load(file)

In [40]:
import os

print(os.getcwd())

C:\Users\Om\books-project\scikit-learn\scikit_youtube

In [41]:
import os

print(os.path.exists('logistic_model.pkl'))

True

# calssification

User/input value
      ↓
Python variable ........ remeber this
      ↓
Dictionary
      ↓
DataFrame
      ↓
Preprocessing
      ↓
Model
      ↓
Prediction

In [42]:
gender = 'female'
SeniorCitizen = 'No'
Partner = 'Yes'
Dependents = 'No'
tenure = 1
PhoneService = 'No'
MultipleLines = 'No Phone Service'
Contract = 'month-to-month'
TotalCharges = 25.05

# first make the variables before giving them into dictionary

In [43]:
data = {
    'gender': [gender],
    'SeniorCitizen': [SeniorCitizen],
    'Partner': [Partner],
    'Dependents': [Dependents],
    'tenure': [tenure],
    'PhoneService': [PhoneService],
    'MultipleLines': [MultipleLines],
    'Contract': [Contract],
    'TotalCharges': [TotalCharges]
}

df1 = pd.DataFrame(data)

In [44]:
df1# this is individual detail we encode it to get our answer as 0(no churn) or 1 (churn)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges
0,female,No,Yes,No,1,No,No Phone Service,month-to-month,25.05

In [45]:
def predictive(gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges):# we created a function and called it based on our features 
    data={
        'gender':[gender],	# 'gender': is colm name and [gender]='female' (we are passing value in it)
        'SeniorCitizen':[SeniorCitizen],	
        'Partner':[Partner],
        'Dependents':[Dependents],
        'tenure':[tenure],
        'PhoneService':[PhoneService],
        'MultipleLines':[MultipleLines],	
        'Contract':	[Contract],
        'TotalCharges':[TotalCharges]
    }
    df1=pd.DataFrame(data)

    categorical_colms=['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','Contract','TotalCharges']
    for colms in categorical_colms:
        df1[colms]= label_encoder.fit_transform(df1[colms])
    

    df1=scalar.fit_transform(df1)
    result=lg.predict(df1).reshape(1,-1)
    return result[0]

In [46]:
df.iloc[0].values # this data is in form of 0 and 1's

array([ 0.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  , 29.85,
        0.  ])

In [47]:
gender = 'female'
SeniorCitizen = 'No'
Partner = 'Yes'
Dependents = 'No'
tenure = 1
PhoneService = 'No'
MultipleLines = 'No Phone Service'
Contract = 'month-to-month'
TotalCharges = 2505

result=predictive(gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges)

if result==0:
    print("Not Churn")
else:
    print('Churn')

Not Churn

In [48]:
# result = array([0)]

In [49]:
from sklearn.utils.validation import check_is_fitted

try:
    check_is_fitted(lg)
    print("Model is fitted")
except Exception as e:
    print("Model is NOT fitted:", e)

Model is fitted

above error because you reran some cells and trained block is missed when ran only few cells

In [1]:
# reamaining learn to use fastapi and streamlit